const menu = [
    {
      id: 1,
      title: 'Avatar',
      category: 'Fantasy',
      price: 9.99,
      img: 'https://image.slidesharecdn.com/presentation-avatarfilmposteranalysis-150303060114-conversion-gate01/95/avatar-film-poster-analysis-1-638.jpg?cb=1425363082',
      desc: `A paraplegic Marine dispatched to the moon Pandora on a unique mission becomes torn between following his orders and protecting the world he feels is his home. `,
    },
    {
      id: 2,
      title: 'John Wick',
      category: 'Action',
      price: 7.99,
      img: 'https://www.vintagemovieposters.co.uk/wp-content/uploads/2020/07/IMG_8410-scaled.jpeg',
      desc: `An ex-hit-man comes out of retirement to track down the gangsters that killed his dog and took everything from him. `,
    },
    {
      id: 3,
      title: 'Iron Man',
      category: 'Action',
      price: 6.99,
      img: 'https://501mustseemoviesproject.files.wordpress.com/2013/05/iron-man-2008.jpeg',
      desc: `After being held captive in an Afghan cave, billionaire engineer Tony Stark creates a unique weaponized suit of armor to fight evil.`,
    },
    {
      id: 4,
      title: 'Thor',
      category: 'Fantasy',
      price: 5.99,
      img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRdY5CP9eJkd3NjCav-6rfLQlI1ieI-2Vm7mg&usqp=CAU',
      desc: `The powerful but arrogant god Thor is cast out of Asgard to live amongst humans in Midgard (Earth), where he soon becomes one of their finest defenders.`,
    },
    {
      id: 5,
      title: 'The Man From UNCLE',
      category: 'Adventure',
      price: 4.99,
      img: 'https://www.hometheaterforum.com/community/media/2015-man-from-uncle-quad-poster.2548/full',
      desc: `In the early 1960s, CIA agent Napoleon Solo and KGB operative Illya Kuryakin participate in a joint mission against a mysterious criminal organization, which is working to proliferate nuclear weapons.`,
    },
    {
      id: 6,
      title: 'La La Land',
      category: 'Drama',
      price: 5.99,
      img: 'https://kmscubreporter.com/wp-content/uploads/2017/03/lalaland.jpg',
      desc: `While navigating their careers in Los Angeles, a pianist and an actress fall in love while attempting to reconcile their aspirations for the future.`,
    },
    {
      id: 7,
      title: 'I Am Sam',
      category: 'Drama',
      price: 4.99,
      img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQh3psRZvdednV654y1-GyYPtvJmZZ5H5BTJQ&usqp=CAU',
      desc: `carry jianbing normcore freegan. Viral single-origin coffee live-edge, pork belly cloud bread iceland put a bird `,
    },
    {
      id: 8,
      title: 'The Nun',
      category: 'Horror',
      price: 8.99,
      img: 'https://www.shmoti.com/ImageFiles/Image_555x271/20180902_Banner_Nun20180902.jpg',
      desc: `A priest with a haunted past and a novice on the threshold of her final vows are sent by the Vatican to investigate the death of a young nun in Romania and confront a malevolent force in the form of a demonic nun. `,
    },
    {
      id: 9,
      title: 'Shrek',
      category: 'Animation',
      price: 9.99,
      img: 'https://www.kindpng.com/picc/m/49-494564_shrek-shrek-movie-poster-landscape-hd-png-download.png',
      desc: `A mean lord exiles fairytale creatures to the swamp of a grumpy ogre, who must go on a quest and rescue a princess for the lord in order to get his land back.`,
    },
  ];
  export default menu;